spring.application.name=TaskTrackerBot
server.port=8081
spring.main.web-application-type=none
# URL for the main task tracker API
task-tracker.api.url=http://localhost:8080
internal.api.key = ${INTERNAL_API_KEY}
# API token for Telegram API
bot.secret=${bot_token}
# Token for generating a HMAC handshake
api.hmac = ${API_handshake_token}
# Redis
spring.data.redis.host=redis-bot
spring.data.redis.port=6380
# Debug
logging.level.org.example.tasktrackerbot=DEBUG
logging.level.org.springframework.web.client.RestClient=DEBUG
# Profiles
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}