spring.application.name=TaskTrackerBot
server.port=8081
spring.main.web-application-type=none
# URL for the main task tracker API
task-tracker.api.url=http://localhost:8080
# API token for Telegram API
bot.secret=${bot_token}
# Token for generating a HMAC handshake
api.hmac = ${API_handshake_token}
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
# Debug
logging.level.org.example.tasktrackerbot=DEBUG

