task-tracker.api.url=http://task-tracker-app:8080

spring.data.redis.host=redis-bot
spring.data.redis.port=6379
#Sentry
sentry.dsn=${SENTRY_LINK}
sentry.environment=production
sentry.send-default-pii=true
sentry.logging.minimum-event-level=error
sentry.tags.server-name=bot
sentry.server-name=task-tracker-bot
sentry.traces-sample-rate=0.5