task-tracker.api.url=http://localhost:8080

spring.data.redis.host=localhost
spring.data.redis.port=6380

logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.apache.hc.client5.http=DEBUG